# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
      - production
  paths:
    include:
      - /*

schedules:
 - cron: "0 14 * * 5" # UTC 1-5 for weekdays.
   displayName: 'Friday - Build'
   branches:
     include:
     - main # will use production once development branch has some features implemented.
   always: true

pr:
- '*'

jobs:
- job: Run
  displayName: 'Run main file'
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: UsePythonVersion@0
    displayName: 'Install Python 3.8'
    inputs:
      versionSpec: '3.8'
  - script: pip install -r requirements.txt
    displayName: 'Use correct environment.'
  - script: python main.py -a $(SF_ACCOUNT) -u $(SF_USERNAME) -w $(SF_WAREHOUSE) -d $(SF_DATABASE) -s $(SF_SCHEMA) -r $(SF_ROLE) -p $(SF_PWD)
    displayName: 'SF Session running...'


